// A játék 100 szópáros brutál adatbázisa - Nagy kontrasztokkal!

const wordPairs = [
    // --- 🚜 NÉPIES / RÉGIES vs MODERN / KÜLÖNBÖZŐ (25 db) ---
    { a: "Kemence", b: "Mikrohullámú sütő" },
    { a: "Lovaskocsi", b: "Elektromos roller" },
    { a: "Fapapucs", b: "Magassarkú cipő" },
    { a: "Várkastély", b: "Panelház" },
    { a: "Kút", b: "Okoscsap" },
    { a: "Fonó (összejövetel)", b: "Techno buli" },
    { a: "Petróleumlámpa", b: "RGB Led szalag" },
    { a: "Sublót (komód)", b: "IKEA szerkény" },
    { a: "Pásztor", b: "Kripto-bróker" },
    { a: "Krumpliföld", b: "Konditerem" },
    { a: "Távirat", b: "Snapchat üzenet" },
    { a: "Puliszka", b: "Avokádós pirítós" },
    { a: "Kard", b: "Lézerpisztoly" },
    { a: "Banya", b: "Instagram modell" },
    { a: "Kisbíró", b: "TikToker" },
    { a: "Batyu", b: "Gucci táska" },
    { a: "Lajbi (mellény)", b: "Pufidzseki" },
    { a: "Koma (barát)", b: "Tinder matcs" },
    { a: "Boszorkány", b: "Tündérkeresztanya" },
    { a: "Ispán", b: "Multinacionális vezérigazgató" },
    { a: "Malacpersely", b: "Bankszámla" },
    { a: "Kalamáris (tintatartó)", b: "Lézernyomtató" },
    { a: "Betyár", b: "Utcai bandatag" },
    { a: "Gatyarotyogtató hideg", b: "Klímaberendezés" },
    { a: "Kukutyin (világvége)", b: "New York" },

    // --- 📱 VADHÜLYE SLENG vs HAGYOMÁNYOS (25 db) ---
    { a: "NPC (háttérszereplő)", b: "A falu bolondja" },
    { a: "Cringe (kínos)", b: "Büszkeség" },
    { a: "Flexel (felvág)", b: "Szerénykedik" },
    { a: "Boomer (öreges)", b: "Óvodás" },
    { a: "Chad (alfahím)", b: "Papucs (férj)" },
    { a: "Ghosting (felszívódás)", b: "Házasságkötés" },
    { a: "Skibidi (agyament)", b: "Tudományos értekezés" },
    { a: "Vibe (hangulat)", b: "Depresszió" },
    { a: "Gyatt (nagy fenék)", b: "Sörhas" },
    { a: "Toxikus kapcsolat", b: "Holtomiglan-holtodiglan" },
    { a: "Mewing (állkapocs torna)", b: "Műfogsor" },
    { a: "Influencer", b: "Pap (lelkész)" },
    { a: "Podcast", b: "Pletykálkodás a piacon" },
    { a: "E-sport", b: "Gombfoci" },
    { a: "VR Szemüveg", b: "Olvasószemüveg" },
    { a: "Salty (sértődött)", b: "Végtelenül boldog" },
    { a: "Red flag (intő jel)", b: "Zöld lámpa" },
    { a: "Main character (főszereplő)", b: "Statiszta" },
    { a: "Delulu (téveszmés)", b: "Földhözragadt" },
    { a: "Bussin (nagyon finom)", b: "Ehetetlen moslék" },
    { a: "Kézműves sör", b: "Kőbányai világos" },
    { a: "Matcha latte", b: "Házi pálinka" },
    { a: "Home office", b: "Szénbánya" },
    { a: "Gluténmentes", b: "Töltött káposzta" },
    { a: "OnlyFans", b: "Zárda (apácáknak)" },

    // --- 🤣 ABSZURD ÉS VICCES KONTASZTOK (25 db) ---
    { a: "Tengerjáró hajó", b: "Felfújható gumicsónak" },
    { a: "Helikopter", b: "Papírrepülő" },
    { a: "Oroszlán", b: "Tengerimalac" },
    { a: "Tűzhányó", b: "Tábortűz" },
    { a: "Kaszinó", b: "Játszótér" },
    { a: "Őserdő", b: "Műanyag szobanövény" },
    { a: "Kaviár", b: "Vajas kenyér" },
    { a: "Pezsgőfürdő", b: "Pocsolya" },
    { a: "Limuzin", b: "Talicska" },
    { a: "Gyémántgyűrű", b: "Műanyag vonalzó" },
    { a: "Kastély", b: "Karton doboz" },
    { a: "Ferrari", b: "BKV busz" },
    { a: "Torta", b: "Száraz zsemle" },
    { a: "Mesterlövész", b: "Óvónő" },
    { a: "Szenteltvíz", b: "Vodka" },
    { a: "Hóember", b: "Madárijesztő" },
    { a: "Zombiapokalipszis", b: "Nátha" },
    { a: "Börtön", b: "Kollégium" },
    { a: "Temető", b: "Vidámpark" },
    { a: "Lottónyemény", b: "Adótartozás" },
    { a: "Fogorvos", b: "Fodrász" },
    { a: "Kaktusz", b: "Selyempárna" },
    { a: "WC-papír", b: "Csiszolópapír" },
    { a: "Bikini", b: "Hóember-jelmez" },
    { a: "Mentőautó", b: "Jégkrémes kocsi" },

    // --- 🧠 HÉTKÖZNAPI, DE MEGTÉVESZTŐ KATEGÓRIÁK (25 db) ---
    { a: "Kocsma", b: "Könyvtár" },
    { a: "Keresztelő", b: "Legénybúcsú" },
    { a: "Szauna", b: "Hűtőkamra" },
    { a: "Naptej", b: "Majonéz" },
    { a: "Szúnyog", b: "Vámpír" },
    { a: "Kukásautó", b: "Esküvői hintó" },
    { a: "Fogkefe", b: "WC-kefe" },
    { a: "Távirányító", b: "Varázspálca" },
    { a: "Hálózsák", b: "Szemeteszsák" },
    { a: "Király", b: "Koldus" },
    { a: "Rendőr", b: "Betörő" },
    { a: "Orvos", b: "Sámán" },
    { a: "Tanár", b: "Diák" },
    { a: "Szakács", b: "Kannibál" },
    { a: "Szülinap", b: "Matematika vizsga" },
    { a: "Koncert", b: "Némafilm" },
    { a: "Tüzijáték", b: "Áramszünet" },
    { a: "Földrengés", b: "Hátmasszázs" },
    { a: "Mágia", b: "Fizika" },
    { a: "Cápa", b: "Aranyhal" },
    { a: "Porszívó", b: "Lombfúvó" },
    { a: "Dezodor", b: "Rovarirtó spray" },
    { a: "Tükör", b: "Ablak" },
    { a: "Pelenka", b: "Felnőtt pelenka" },
    { a: "Anyós", b: "Házisárkány" }
];